apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mqivt 
spec:
  source:
    git:
      uri: https://github.com/peterajessup/cp4idemomq
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.0.0-r1-amd64"
      pullSecret:
        name: ibm-entitlement-key
  output:
    to:
      kind: ImageStreamTag
      name: 'mqivt:v1.1'
